services:
  mqtt-broker:
    image: eclipse-mosquitto@sha256:38c0da4f2ef84284d47b3b3eeea1cb3bdeabe81ee10caf0cd5c5ff61ee3ea408
    volumes:
      - ./config/mosquitto:/mosquitto/config:ro
      - mqtt-data:/mosquitto/data
      - mqtt-log:/mosquitto/log
    networks:
      - mqtt--sensors
      - mqtt--backend
    ports:
      - 18883:8883

  history-db:
    image: couchdb@sha256:8cf5f8442585c346d2717ff0ad95605731d2f19f67b8367840baa8d3b24ebc31
    volumes:
      - history-data:/opt/couchdb/data
    networks:
      - history--prediction
      - history--backend
    environment:
      COUCHDB_USER: ${COUCHDB_USER}
      COUCHDB_PASSWORD: ${COUCHDB_PASSWORD}

  dashboard:
    image: node@sha256:0a7108bf6c7bf5de370ffb1a3ed6be93d405b43ff159f681a8d18c0e2bc2e402
    networks:
      - dashboard--backend
    ports:
      -10443:80
    
  backend:
    build:
      context: https://github.com/ESPI-Workshop-Vig1l-8/backend.git#main
    image: sentinel/backend:main
    volumes:
      - backend-data:/var/lib/backend
    networks:
      - history--backend
      - dashboard--backend
      - mqtt--backend
      - vision--backend

  ia-vision:
    image: python@sha256:d9368b3a5ac59afea7b5d4f2e2aea0941dbf9fdee9c369c5bec00b98244bc929
    volumes:
      - vision-models:/models:ro
      - vision-cache:/root/.cache
    networks:
      - vision--backend

  ia-prediction:
    image: python@sha256:d9368b3a5ac59afea7b5d4f2e2aea0941dbf9fdee9c369c5bec00b98244bc929
    volumes:
      - prediction-models:/models
      - prediction-cache:/root/.cache
    networks:
      - history--prediction

  # reverse-proxy:
  #   image: nginx:latest
  #   volumes:
  #     - ./config/nginx:/etc/nginx/conf.d:ro
  #     - proxy-certs:/etc/letsencrypt

networks:
  history--prediction:
  history--backend:
  dashboard--backend:
  mqtt--backend:
  mqtt--sensors:
  vision--backend:

volumes:
  mqtt-data:
  mqtt-log:
  history-data:
  backend-data:
  vision-models:
  vision-cache:
  prediction-models:
  prediction-cache: